
CREATE SEQUENCE USERS_SEQ_1;
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('myemail12@mail.com','An random user','myemail12@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Conner','Hello. I am from Ireland','myemail23@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Sandra','Life is happiness','myemail34@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Jhonatan','I like hamburger','myemail45@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Erik','Good to meet you','myemail56@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Rick','Im from Scotland','myemail67@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Mateo','Im brazilian and I like football','myemail78@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Paul','I like videogames','myemail89@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Mary','I like photos','myemail90@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Lauren','I like coffee','myemail01@mail.com');

INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('20/12/2011','DD/MM/RRRR'),'A',5,6);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('13/01/2015','DD/MM/RRRR'),'A',5,9);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('04/09/2013','DD/MM/RRRR'),'A',5,14);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('21/10/2018','DD/MM/RRRR'),'A',8,11);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('04/07/2016','DD/MM/RRRR'),'A',10,13);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('30/08/2021','DD/MM/RRRR'),'A',13,14);


INSERT INTO allocation_site(city, address, owner_id) VALUES(25222,'Building Number: 98',5);
INSERT INTO allocation_site(city, address, owner_id) VALUES(44856,'Street Address: Funkturm Berlin',9);
INSERT INTO allocation_site(city, address, owner_id) VALUES(27540,'Puerta 792 Paseo María Cristina, 8 Esc. 746, Hospitalet de LLobregat, Com 40234',10);
INSERT INTO allocation_site(city, address, owner_id) VALUES(35186,'Piazza Italo 151, Appartamento 69, Borgo Sarita, TE 93497',12);
INSERT INTO allocation_site(city, address, owner_id) VALUES(59582,'Incrocio Audenico 1, Piano 7, Fortunata laziale, OR 45264',13);
INSERT INTO allocation_site(city, address, owner_id) VALUES(61422,'Rotonda Fior 63, Marini veneto, CI 257187',14);


INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('20/03/2011','DD/MM/RRRR'),5,6);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('18/04/2013','DD/MM/RRRR'),5,7);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('21/12/2015','DD/MM/RRRR'),5,14);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('13/05/2016','DD/MM/RRRR'),6,11);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('09/06/2018','DD/MM/RRRR'),7,9);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('08/07/2021','DD/MM/RRRR'),7,13);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('04/12/2022','DD/MM/RRRR'),9,14);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('13/05/2022','DD/MM/RRRR'),11,13);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('20/08/2023','DD/MM/RRRR'),12,13);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('13/01/2024','DD/MM/RRRR'),13,14);
INSERT INTO USER_CONTACT(FRIENDS_FROM, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('16/10/2025','DD/MM/RRRR'),14,6);


INSERT INTO TAG(DESCRIPTION) values('City');
INSERT INTO TAG(DESCRIPTION) values('Urban');
INSERT INTO TAG(DESCRIPTION) values('Beach');
INSERT INTO TAG(DESCRIPTION) values('Cold');
INSERT INTO TAG(DESCRIPTION) values('Sunset');
INSERT INTO TAG(DESCRIPTION) values('Winter');
INSERT INTO TAG(DESCRIPTION) values('Summer');
INSERT INTO TAG(DESCRIPTION) values('France');
INSERT INTO TAG(DESCRIPTION) values('Italy');
INSERT INTO TAG(DESCRIPTION) values('Spain');
INSERT INTO TAG(DESCRIPTION) values('Relax');
INSERT INTO TAG(DESCRIPTION) values('Chill');
INSERT INTO TAG(DESCRIPTION) values('Friends');
INSERT INTO TAG(DESCRIPTION) values('Food');
INSERT INTO TAG(DESCRIPTION) values('Music');

INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(28,1); --"Frankfurt am Main"
INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(29,11); --"Munich"
INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(30,6); --"Madrid"
INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(30,10);--"Madrid"
INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(31,13);--"Paris"
INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(31,14);--"Paris"
INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(32,11);--"Rome"
INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(32,14);--"Rome"
INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(32,12);--"Rome"
INSERT INTO ALLOCATION_SITE_TAG(ALLOCATION_SITE_ID, TAG_ID) VALUES(33,14);--"Toscanella"


INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('20/02/2019','DD/MM/YYYY'),'allocation_site',28,4);
INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('13/08/2021','DD/MM/YYYY'),'allocation_site',28,5);
INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('04/06/2023','DD/MM/YYYY'),'allocation_site',29,6);
INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('08/12/2021','DD/MM/YYYY'),'allocation_site',29,7);
INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('09/11/2020','DD/MM/YYYY'),'allocation_site',30,8);
INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('16/07/2022','DD/MM/YYYY'),'allocation_site',30,9);
INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('01/04/2019','DD/MM/YYYY'),'allocation_site',31,9);
INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('06/06/2016','DD/MM/YYYY'),'allocation_site',31,11);
INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('30/04/2023','DD/MM/YYYY'),'allocation_site',32,12);
INSERT INTO user_interactions(registry_date,activity_entity,activity_id,user_id) VALUES(TO_DATE('15/12/2022','DD/MM/YYYY'),'allocation_site',33,12);