-- public.allocation_booking definition

-- Drop table

-- DROP TABLE public.allocation_booking;

CREATE TABLE public.allocation_booking (
	id int8 NOT NULL,
	allocation_site_id int8 NOT NULL,
	start_date date NOT NULL,
	end_date date NOT NULL,
	number_of_persons int4 NOT NULL,
	payment_status char NOT NULL,
	CONSTRAINT allocation_booking_pkey PRIMARY KEY (id),
	CONSTRAINT payment_status_check CHECK ((payment_status = ANY (ARRAY['D'::"char", 'P'::"char", 'T'::"char"])))
);


-- public.category definition

-- Drop table

-- DROP TABLE public.category;

CREATE TABLE public.category (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(150) NULL,
	state varchar(1) NOT NULL,
	CONSTRAINT category_pkey PRIMARY KEY (id)
);


-- public.cities definition

-- Drop table

-- DROP TABLE public.cities;

CREATE TABLE public.cities (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	state_id int8 NOT NULL,
	state_code varchar(255) NOT NULL,
	country_id int8 NOT NULL,
	country_code bpchar(2) NOT NULL,
	latitude numeric(10, 8) NOT NULL,
	longitude numeric(11, 8) NOT NULL,
	timezone varchar(255) NULL,
	created_at timestamp DEFAULT '2014-01-01 12:01:01'::timestamp without time zone NOT NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	flag int2 DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255) NULL
);


-- public.countries definition

-- Drop table

-- DROP TABLE public.countries;

CREATE TABLE public.countries (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	iso3 bpchar(3) NULL,
	numeric_code bpchar(3) NULL,
	iso2 bpchar(2) NULL,
	phonecode varchar(255) NULL,
	capital varchar(255) NULL,
	currency varchar(255) NULL,
	currency_name varchar(255) NULL,
	currency_symbol varchar(255) NULL,
	tld varchar(255) NULL,
	native varchar(255) NULL,
	region varchar(255) NULL,
	region_id int8 NULL,
	subregion varchar(255) NULL,
	subregion_id int8 NULL,
	nationality varchar(255) NULL,
	timezones text NULL,
	translations text NULL,
	latitude numeric(10, 8) NULL,
	longitude numeric(11, 8) NULL,
	emoji varchar(191) NULL,
	"emojiU" varchar(191) NULL,
	created_at timestamp NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	flag int2 DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255) NULL
);


-- public.regions definition

-- Drop table

-- DROP TABLE public.regions;

CREATE TABLE public.regions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	translations text NULL,
	created_at timestamp NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	flag int2 DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255) NULL
);


-- public.states definition

-- Drop table

-- DROP TABLE public.states;

CREATE TABLE public.states (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	country_id int8 NOT NULL,
	country_code bpchar(2) NOT NULL,
	fips_code varchar(255) NULL,
	iso2 varchar(255) NULL,
	iso3166_2 varchar(10) NULL,
	"type" varchar(191) NULL,
	"level" int4 NULL,
	parent_id int8 NULL,
	native varchar(255) NULL,
	latitude numeric(10, 8) NULL,
	longitude numeric(11, 8) NULL,
	timezone varchar(255) NULL,
	created_at timestamp NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	flag int2 DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255) NULL
);


-- public.subregions definition

-- Drop table

-- DROP TABLE public.subregions;

CREATE TABLE public.subregions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(100) NOT NULL,
	translations text NULL,
	region_id int8 NOT NULL,
	created_at timestamp NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	flag int2 DEFAULT 1 NOT NULL,
	"wikiDataId" varchar(255) NULL
);


-- public.tag definition

-- Drop table

-- DROP TABLE public.tag;

CREATE TABLE public.tag (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(100) NOT NULL,
	state varchar(1) DEFAULT 'A'::character varying NOT NULL,
	creation_date date DEFAULT now() NOT NULL,
	CONSTRAINT tag_pkey PRIMARY KEY (id)
);


-- public.user_tags definition

-- Drop table

-- DROP TABLE public.user_tags;

CREATE TABLE public.user_tags (
	user_id int8 NOT NULL,
	tag_id int8 NOT NULL,
	status char DEFAULT 'A'::"char" NOT NULL,
	created date DEFAULT now() NULL,
	CONSTRAINT user_tags_pkey PRIMARY KEY (user_id, tag_id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	username varchar(30) NULL,
	user_rating numeric(3, 1) DEFAULT 0.0 NOT NULL,
	description varchar(150) NULL,
	email varchar(40) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.allocation_site definition

-- Drop table

-- DROP TABLE public.allocation_site;

CREATE TABLE public.allocation_site (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	city int8 NOT NULL,
	address varchar(150) NOT NULL,
	owner_id int4 NOT NULL,
	CONSTRAINT allocation_site_pkey PRIMARY KEY (id),
	CONSTRAINT allocation_site_owner_id_40fbab5b_fk_users_id FOREIGN KEY (owner_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX allocation_site_owner_id_40fbab5b ON public.allocation_site USING btree (owner_id);


-- public.allocation_site_tag definition

-- Drop table

-- DROP TABLE public.allocation_site_tag;

CREATE TABLE public.allocation_site_tag (
	allocation_site_id int8 NOT NULL,
	tag_id int8 NOT NULL,
	priority int8 DEFAULT 1 NOT NULL,
	CONSTRAINT allocation_site_tag_pkey PRIMARY KEY (allocation_site_id, tag_id, priority),
	CONSTRAINT allocation_site_id_fk FOREIGN KEY (allocation_site_id) REFERENCES public.allocation_site(id),
	CONSTRAINT tag_id FOREIGN KEY (tag_id) REFERENCES public.tag(id)
);


-- public.category_priority definition

-- Drop table

-- DROP TABLE public.category_priority;

CREATE TABLE public.category_priority (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	priority int4 NOT NULL,
	allocation_site_id int8 NULL,
	category_id int8 NULL,
	CONSTRAINT category_priority_pkey PRIMARY KEY (id),
	CONSTRAINT "category_priority_allocationSite_id_1e739acf_fk_allocatio" FOREIGN KEY (allocation_site_id) REFERENCES public.allocation_site(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT category_priority_category_id_42e69dcc_fk_category_id FOREIGN KEY (category_id) REFERENCES public.category(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX "category_priority_allocationSite_id_1e739acf" ON public.category_priority USING btree (allocation_site_id);
CREATE INDEX category_priority_category_id_42e69dcc ON public.category_priority USING btree (category_id);


-- public.media_data definition

-- Drop table

-- DROP TABLE public.media_data;

CREATE TABLE public.media_data (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	insert_date date NOT NULL,
	state varchar NOT NULL,
	"content" bytea NULL,
	allocation_id int8 NOT NULL,
	url varchar NULL,
	CONSTRAINT media_data_pkey PRIMARY KEY (id),
	CONSTRAINT media_data_allocation_id_id_64131889_fk_allocation_site_id FOREIGN KEY (allocation_id) REFERENCES public.allocation_site(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX media_data_allocation_id_id_64131889 ON public.media_data USING btree (allocation_id);


-- public.rating definition

-- Drop table

-- DROP TABLE public.rating;

CREATE TABLE public.rating (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	rating numeric(3, 1) NOT NULL,
	"comment" varchar(150) NULL,
	allocation_id int8 NULL,
	user_id int4 NULL,
	CONSTRAINT rating_pkey PRIMARY KEY (id),
	CONSTRAINT rating_allocation_id_18b83c7c_fk_allocation_site_id FOREIGN KEY (allocation_id) REFERENCES public.allocation_site(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT rating_user_id_029b834f_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX rating_allocation_id_18b83c7c ON public.rating USING btree (allocation_id);
CREATE INDEX rating_user_id_029b834f ON public.rating USING btree (user_id);


-- public.user_contact definition

-- Drop table

-- DROP TABLE public.user_contact;

CREATE TABLE public.user_contact (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	friends_from date NOT NULL,
	status varchar DEFAULT 'A'::character varying NOT NULL,
	first_user_id int4 NOT NULL,
	second_user_id int4 NOT NULL,
	CONSTRAINT user_contact_pkey PRIMARY KEY (id),
	CONSTRAINT user_contact_friend_id_id_62bfada2_fk_users_id FOREIGN KEY (first_user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT user_contact_user_id_id_6633f570_fk_users_id FOREIGN KEY (second_user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX user_contact_friend_id_id_62bfada2 ON public.user_contact USING btree (first_user_id);
CREATE INDEX user_contact_user_id_id_6633f570 ON public.user_contact USING btree (second_user_id);


-- public.user_interactions definition

-- Drop table

-- DROP TABLE public.user_interactions;

CREATE TABLE public.user_interactions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	registry_date date NOT NULL,
	activity_entity char NOT NULL,
	activity_id int4 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT user_interaction_pkey PRIMARY KEY (id),
	CONSTRAINT user_interaction_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.user_reactions definition

-- Drop table

-- DROP TABLE public.user_reactions;

CREATE TABLE public.user_reactions (
	id int8 NOT NULL,
	user_id int8 NOT NULL,
	allocation_id int8 NOT NULL,
	reaction_type varchar(2) NOT NULL,
	reaction_date date DEFAULT now() NOT NULL,
	parent_reaction_id int8 NULL,
	CONSTRAINT user_reactions_pkey PRIMARY KEY (id),
	CONSTRAINT allocation_site_id_fk FOREIGN KEY (allocation_id) REFERENCES public.allocation_site(id),
	CONSTRAINT parent_reaction_id_fk FOREIGN KEY (parent_reaction_id) REFERENCES public.user_reactions(id),
	CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);
