SELECT * FROM USERS;
SELECT * FROM ALLOCATION_SITE;
SELECT * FROM MEDIA_DATA;
SELECT * FROM USER_CONTACT;
SELECT * FROM countries;
SELECT * FROM states ORDER BY name DESC;
SELECT * FROM cities;

SELECT s.id, s.name, s.country_id, c.name, s.id as countryid, s.country_code, c.iso3 FROM STATES S 
join countries c on s.country_id=c.id
where c.name like 'Col%'
order by c.name, s.name;
SELECT * FROM STATES WHERE NAME='Żejtun'

CREATE SEQUENCE USERS_SEQ_1;
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('myemail12@mail.com','An random user','myemail12@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Conner','Hello. I am from Ireland','myemail23@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Sandra','Life is happiness','myemail34@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Jhonatan','I like hamburger','myemail45@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Erik','Good to meet you','myemail56@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Rick','Im from Scotland','myemail67@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Mateo','Im brazilian and I like football','myemail78@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Paul','I like videogames','myemail89@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Mary','I like photos','myemail90@mail.com');
INSERT INTO USERS(USERNAME, DESCRIPTION, EMAIL) VALUES('Lauren','I like coffee','myemail01@mail.com');

INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('20/12/2011','DD/MM/RRRR'),'A',5,6);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('13/01/2015','DD/MM/RRRR'),'A',5,9);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('04/09/2013','DD/MM/RRRR'),'A',5,14);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('21/10/2018','DD/MM/RRRR'),'A',8,11);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('04/07/2016','DD/MM/RRRR'),'A',10,13);
INSERT INTO USER_CONTACT(FRIENDS_FROM, STATUS, FIRST_USER_ID, SECOND_USER_ID) VALUES(TO_DATE('30/08/2021','DD/MM/RRRR'),'A',13,14);

INSERT INTO STATE(NAME, COUNTRY_ID) VALUES('', SELECT ID FROM COUNTRY WHERE UPPER(NAME)='');
INSERT INTO STATE(NAME, COUNTRY_ID) VALUES('', SELECT ID FROM COUNTRY WHERE UPPER(NAME)='');



INSERT INTO ALLOCATION_SITE(CITY,ADDRESS,OWNER_ID) VALUES('','',);