# Generated by Django 4.2.23 on 2025-09-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'allocation_site',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(default=1, max_length=1)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=1)),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, error_messages='The username is required', max_length=30)),
                ('user_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(default='*', max_length=40)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('allocation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.allocationsite')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.user')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='MediaData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('insert_date', models.DateField()),
                ('state', models.CharField()),
                ('content', models.BinaryField()),
                ('allocation_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.allocationsite')),
            ],
            options={
                'db_table': 'media_data',
            },
        ),
        migrations.CreateModel(
            name='CategoryPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('allocationSite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.allocationsite')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.category')),
            ],
            options={
                'db_table': 'category_priority',
            },
        ),
        migrations.CreateModel(
            name='AllocationSiteTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_site_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.allocationsite')),
                ('tag_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.tag')),
            ],
        ),
        migrations.AddField(
            model_name='allocationsite',
            name='owner',
            field=models.ForeignKey(default=None, error_messages='Please provide an owner for this allocation', on_delete=django.db.models.deletion.PROTECT, to='rubberroom.user'),
        ),
    ]
