# Generated by Django 4.2.23 on 2025-09-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='allocation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.allocationsite'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.user'),
        ),
    ]
