# Generated by Django 4.2.23 on 2025-09-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationbooking',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='allocationsite',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='allocationsitetags',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='categorypriority',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mediadata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usercontact',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userinteractions',
            options={'managed': False},
        ),
    ]
