# Generated by Django 4.2.23 on 2025-09-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationsite',
            name='owner',
            field=models.ForeignKey(default=None, error_messages={'Error': 'Please provide an owner for this allocation'}, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.user'),
        ),
    ]
