# Generated by Django 4.2.23 on 2025-09-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
