# Generated by Django 4.2.23 on 2025-09-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0002_rating_allocation_rating_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=1)),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='allocationsite',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.user'),
        ),
        migrations.AddField(
            model_name='categorypriority',
            name='allocationSite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.allocationsite'),
        ),
        migrations.AddField(
            model_name='categorypriority',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.category'),
        ),
        migrations.CreateModel(
            name='AllocationSiteTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_site_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.allocationsite')),
                ('tag_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rubberroom.tag')),
            ],
        ),
    ]
