# Generated by Django 4.2.23 on 2025-09-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0003_country_state_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'managed': False},
        ),
    ]
