# Generated by Django 4.2.23 on 2025-09-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0004_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
        migrations.AlterModelTable(
            name='state',
            table='states',
        ),
    ]
