# Generated by Django 4.2.23 on 2025-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0005_alter_city_table_alter_country_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LI', 'Like'), ('LO', 'Love'), ('RE', 'I recommend'), ('DI', 'Dislike'), ('SU', 'Surprise'), ('CO', 'Comment')], default=None)),
                ('reaction_date', models.CharField()),
                ('parent_reaction_id', models.BigIntegerField(db_comment='The main comment id on a post', default=None, verbose_name='self')),
            ],
            options={
                'db_table': 'user_site_reaction',
                'managed': False,
            },
        ),
    ]
