# Generated by Django 4.2.23 on 2025-09-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0006_userreactions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userreactions',
            table='user_reactions',
        ),
    ]
