# Generated by Django 4.2.23 on 2025-09-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubberroom', '0007_alter_userreactions_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSiteInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_from', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')])),
            ],
            options={
                'db_table': 'user_site_interests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')])),
                ('created', models.DateField()),
            ],
            options={
                'db_table': 'user_tags',
                'managed': False,
            },
        ),
    ]
